name: typescript-action
description: Template of TypeScript Action

inputs:
  name:
    description: example input
    required: true

runs:
  using: 'node20'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
