name: docker-mount-cache-action / save
description: Save the cache of --mount=type=cache to a remote registry

inputs:
  path:
    description: Target path of `--mount=type=cache`
    required: true
  tags:
    description: Push a cache image to tags
    required: true
  internal-mode:
    description: (Internal) This should be save
    default: save

runs:
  using: 'node20'
  main: '../dist/index.js'
