name: e2e-test

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - '**/action.yaml'
      - .github/workflows/e2e-test.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - '**/action.yaml'
      - .github/workflows/e2e-test.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
      - run: corepack enable pnpm
      - run: pnpm i
      - run: pnpm build

      - uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0
      - uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}

      - name: int128/docker-mount-cache-action/restore
        uses: ./restore
        with:
          path: /root/.cache/go-build
          tags: ghcr.io/${{ github.repository }}:go-build-cache

      - uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures

      - name: int128/docker-mount-cache-action/save
        uses: ./save
        with:
          path: /root/.cache/go-build
          tags: ghcr.io/${{ github.repository }}:go-build-cache
